### ISSUE TITLE
Nicknames column labels are incorrectly drawn

### ISSUE THREAD

**Issue by TurBoss** [springlobby/springlobby#935] opened 2019-12-12 20:52 UTC
Hello,

this is how it looks

![imagen](https://user-images.githubusercontent.com/184088/70747974-57ac5d80-1d29-11ea-92a4-38c1e3eccabf.png)

but if you try to resize a column to the left it goes wrong

![imagen](https://user-images.githubusercontent.com/184088/70748015-6b57c400-1d29-11ea-87eb-80b2b373a7dd.png)

only tested on windows 10

**Comment by TurBoss** [comment] 2019-12-12 20:54
it only happends on chat user list

**Comment by silentwings** [comment] 2020-01-06 15:13
Also, in the battle list the "player count" column has lost its label (and a few others too)

**Comment by abma** [comment] 2020-01-12 23:40
duplicate of #942 ?

can you please test
https://github.com/springlobby/springlobby/issues/942#issuecomment-573470693
?

**Comment by TurBoss** [comment] 2020-01-14 06:52
latest develop works like a charm!

**Comment by TurBoss** [comment] 2020-01-23 05:40
this is from the devel channerl
![imagen](https://user-images.githubusercontent.com/184088/72959626-3e2c1600-3dab-11ea-9034-196e587c18de.png)

**Comment by TurBoss** [comment] 2020-01-24 02:44
can this be closed?

**Closed** 2020-01-27 21:36 UTC
Labels: feedback, windows
