### ISSUE TITLE
Latest Springlobby (0.269) is incomatible to old uberserver instances

### ISSUE THREAD

**Issue by icexuick** [springlobby/springlobby#938] opened 2019-12-20 09:45 UTC
Latest version upgrade to 0.269 is very broken.

- Chat partly works
- Battle names and games aren't shown
- Game versions aren't detected and cannot be (re) downloaded
- When closing battle-chat-tab SL crashes

Tested on roadflag.bnr.la:8200

**Comment by abma** [comment] 2019-12-20 09:53
i've never heard about this lobby server, the server needs to be upgraded to the latest version i guess.

very likely this commit is required to fix it:
https://github.com/spring/uberserver/commit/221c826f07be5541d1351a05d5e67b10663820fd

very likely this commit broke it on client side:

https://github.com/springlobby/springlobby/commit/24c683c42df9eb1d0baa66bbb26708d8310431bf

**Comment by abma** [comment] 2019-12-20 09:54
i don't see how this could be fixed by springlobby -> upgrade the lobby server please

**Comment by abma** [comment] 2019-12-20 10:05
please contact the server owner to update ubserver. i can't help with this problem sorry.

**Closed by abma** 2019-12-20 10:05 UTC

**Comment by icexuick** [comment] 2019-12-20 11:03
Thanks for the replies! We will try and search there!
(PS. it's the development server for BAR)

**Comment by silentwings** [comment] 2019-12-24 21:37
> Latest Springlobby (0.269) is incomatible to old uberserver instances

This is intended behaviour.

In general: The latest SL and the latest uberserver versions will be compatible but nothing more is guaranteed.
