### ISSUE TITLE
E-Mail is require for registration

### ISSUE THREAD

**Issue by Hierosme** [springlobby/springlobby#952] opened 2020-04-18 10:13 UTC
Hello,

i have test SpringLobby, and unfortunally a E-Mail address is require for registration.
But it look like a bad joke because it have nothing for enter a e-mail.

I have test vers 267 and 268(snap) and that the same.

Unfortunally it simply kill Spring games.

**Comment by abma** [comment] 2020-05-24 09:30
the email field was introduced in springlobby 0.268, so thats the minimum version to use. can you provide springlobby.log please?

are you sure this is springlobby 0.268?


springlobby 0.268 was released 2019-02-04 but the snap was last updated in 2018: so the version from the snap is wrong i guess.

**Comment by abma** [comment] 2020-05-24 09:31
in short: update springlobby to the latest version, and then there is a field for the email address.

**Comment by Hierosme** [comment] 2020-05-25 17:50
Unfortunally is can't update to 0.268 that because Debian haven't last version is **0.267+dfsg-1+b1**

Then it look i have test with last Debian and last Snap installation.

Unfortunally i can't do other thing...

Do you have a updated Debian package ?

**Comment by abma** [comment] 2020-05-26 18:37
no, sorry.

maybe the package from debian 11 works: https://packages.debian.org/bullseye/springlobby

**Comment by abma** [comment] 2020-06-19 20:59
as alternative you can compile from source:

https://github.com/springlobby/springlobby/wiki/Installfromsource#Debian_10
+
https://github.com/springlobby/springlobby/wiki/Installfromsource#Building_from_Git

**Comment by abma** [comment] 2020-06-23 20:32
basicly a duplicate of #964

**Closed by abma** 2020-06-23 20:32 UTC
Labels: feedback
