### ISSUE TITLE
Ubuntu upgrade to 16.04, Sringlobby do not start any more.

### ISSUE THREAD

**Issue by weingaunity** [springlobby/springlobby#713] opened 2016-04-22 20:20 UTC
The title explains the issue. Up to now i do not have more information.

It worked with Ubuntu 15.04 without any problem.

**Comment by FabriceFABS** [comment] 2016-04-22 20:32
What does means "SL do not start anymore" ?
Run springlobby in the console and return the result, after we could see what is the problem.

**Comment by weingaunity** [comment] 2016-04-23 05:29
Oh, good idea using terminal. Here the output:


springlobby
*** Error in `springlobby': free(): invalid pointer: 0x0000000001025a68 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7fc42c8a1725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7fc42c8a9f4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fc42c8adabc]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x9a)[0x7fc42c86435a]
/home/kw/.spring/engine/101.0/libunitsync.so(+0x81f63)[0x7fc4181b7f63]
======= Memory map: ========
00400000-00a71000 r-xp 00000000 08:05 4851875                            /usr/games/springlobby
00c71000-00c72000 r--p 00671000 08:05 4851875                            /usr/games/springlobby
00c72000-00d1d000 rw-p 00672000 08:05 4851875                            /usr/games/springlobby
00d1d000-00d68000 rw-p 00000000 00:00 0 
00e4a000-0105b000 rw-p 00000000 00:00 0                                  [heap]
7fc414000000-7fc414021000 rw-p 00000000 00:00 0 
7fc414021000-7fc418000000 ---p 00000000 00:00 0 
7fc418136000-7fc418395000 r-xp 00000000 08:05 2907504                    /home/kw/.spring/engine/101.0/libunitsync.so
7fc418395000-7fc4183a6000 rw-p 0025e000 08:05 2907504                    /home/kw/.spring/engine/101.0/libunitsync.so
7fc4183a6000-7fc4185d7000 rw-p 00000000 00:00 0 
7fc4185d7000-7fc41894c000 r-xp 00000000 08:05 2921475                    /home/kw/.spring/engine/100.0/libunitsync.so
7fc41894c000-7fc418b4c000 ---p 00375000 08:05 2921475                    /home/kw/.spring/engine/100.0/libunitsync.so
7fc418b4c000-7fc418b59000 r--p 00375000 08:05 2921475                    /home/kw/.spring/engine/100.0/libunitsync.so
7fc418b59000-7fc418b62000 rw-p 00382000 08:05 2921475                    /home/kw/.spring/engine/100.0/libunitsync.so
7fc418b62000-7fc418e47000 rw-p 00000000 00:00 0 
7fc418e47000-7fc4190a6000 r-xp 00000000 08:05 3033942                    /home/kw/.spring/engine/101.0.1-236-gfaa970b develop/libunitsync.so
7fc4190a6000-7fc4190b7000 rw-p 0025e000 08:05 3033942                    /home/kw/.spring/engine/101.0.1-236-gfaa970b develop/libunitsync.so
7fc4190b7000-7fc4192e8000 rw-p 00000000 00:00 0 
7fc4192e8000-7fc41ab9e000 r-xp 00000000 08:05 4859615                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7fc41ab9e000-7fc41ad9d000 ---p 018b6000 08:05 4859615                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7fc41ad9d000-7fc41ad9e000 r--p 018b5000 08:05 4859615                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7fc41ad9e000-7fc41ad9f000 rw-p 018b6000 08:05 4859615                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7fc41ad9f000-7fc41af1e000 r-xp 00000000 08:05 4858040                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fc41af1e000-7fc41b11e000 ---p 0017f000 08:05 4858040                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fc41b11e000-7fc41b12e000 r--p 0017f000 08:05 4858040                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fc41b12e000-7fc41b12f000 rw-p 0018f000 08:05 4858040                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7fc41b12f000-7fc41b133000 rw-p 00000000 00:00 0 
7fc41b133000-7fc41b385000 r-xp 00000000 08:05 4859583                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7fc41b385000-7fc41b585000 ---p 00252000 08:05 4859583                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7fc41b585000-7fc41b594000 r--p 00252000 08:05 4859583                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7fc41b594000-7fc41b595000 rw-p 00261000 08:05 4859583                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7fc41b595000-7fc41b5e7000 r-xp 00000000 08:05 4859344                    /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.6
7fc41b5e7000-7fc41b7e6000 ---p 00052000 08:05 4859344                    /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.6
7fc41b7e6000-7fc41b7e7000 r--p 00051000 08:05 4859344                    /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.6
7fc41b7e7000-7fc41b7eb000 rw-p 00052000 08:05 4859344                    /usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.6
7fc41b7eb000-7fc41b7ec000 rw-p 00000000 00:00 0 
7fc41b7ec000-7fc41b865000 r-xp 00000000 08:05 4859382                    /usr/lib/x86_64-linux-gnu/libmng.so.2.0.2
7fc41b865000-7fc41ba65000 ---p 00079000 08:05 4859382                    /usr/lib/x86_64-linux-gnu/libmng.so.2.0.2
7fc41ba65000-7fc41ba67000 r--p 00079000 08:05 4859382                    /usr/lib/x86_64-linux-gnu/libmng.so.2.0.2
7fc41ba67000-7fc41ba68000 rw-p 0007b000 08:05 4859382                    /usr/lib/x86_64-linux-gnu/libmng.so.2.0.2
7fc41ba68000-7fc41bb6b000 r-xp 00000000 08:05 4851851                    /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
7fc41bb6b000-7fc41bd6b000 ---p 00103000 08:05 4851851                    /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
7fc41bd6b000-7fc41bd6f000 r--p 00103000 08:05 4851851                    /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
7fc41bd6f000-7fc41bd70000 rw-p 00107000 08:05 4851851                    /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.58.0
7fc41bd70000-7fc41bdd7000 r-xp 00000000 08:05 4856328                    /usr/lib/x86_64-linux-gnu/libIL.so.1.1.0
7fc41bdd7000-7fc41bfd7000 ---p 00067000 08:05 4856328                    /usr/lib/x86_64-linux-gnu/libIL.so.1.1.0
7fc41bfd7000-7fc41bfd8000 r--p 00067000 08:05 4856328                    /usr/lib/x86_64-linux-gnu/libIL.so.1.1.0
7fc41bfd8000-7fc41bfd9000 rw-p 00068000 08:05 4856328                    /usr/lib/x86_64-linux-gnu/libIL.so.1.1.0
7fc41bfd9000-7fc41c08d000 rw-p 00000000 00:00 0 
7fc41c08d000-7fc41c1c2000 r-xp 00000000 08:05 5118174                    /usr/lib/spring/libunitsync.so
7fc41c1c2000-7fc41c1c3000 ---p 00135000 08:05 5118174                    /usr/lib/spring/libunitsync.so
7fc41c1c3000-7fc41c1c7000 r--p 00135000 08:05 5118174                    /usr/lib/spring/libunitsync.so
7fc41c1c7000-7fc41c1c8000 rw-p 00139000 08:05 5118174                    /usr/lib/spring/libunitsync.so
7fc41c1c8000-7fc41c3e5000 rw-p 00000000 00:00 0 
7fc41c3e5000-7fc41c3ee000 r-xp 00000000 08:05 4868469                    /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fc41c3ee000-7fc41c5ed000 ---p 00009000 08:05 4868469                    /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fc41c5ed000-7fc41c5ee000 r--p 00008000 08:05 4868469                    /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fc41c5ee000-7fc41c5ef000 rw-p 00009000 08:05 4868469                    /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1
7fc41c5ef000-7fc41c603000 r-xp 00000000 08:05 4850595                    /usr/lib/x86_64-linux-gnu/libtdb.so.1.3.8
7fc41c603000-7fc41c802000 ---p 00014000 08:05 4850595                    /usr/lib/x86_64-linux-gnu/libtdb.so.1.3.8
7fc41c802000-7fc41c803000 r--p 00013000 08:05 4850595                    /usr/lib/x86_64-linux-gnu/libtdb.so.1.3.8
7fc41c803000-7fc41c804000 rw-p 00014000 08:05 4850595                    /usr/lib/x86_64-linux-gnu/libtdb.so.1.3.8
7fc41c804000-7fc41c814000 r-xp 00000000 08:05 4854585                    /usr/lib/x86_64-linux-gnu/libcanberra.so.0.2.5
7fc41c814000-7fc41ca13000 ---p 00010000 08:05 4854585                    /usr/lib/x86_64-linux-gnu/libcanberra.so.0.2.5
7fc41ca13000-7fc41ca14000 r--p 0000f000 08:05 4854585                    /usr/lib/x86_64-linux-gnu/libcanberra.so.0.2.5
7fc41ca14000-7fc41ca15000 rw-p 00010000 08:05 4854585                    /usr/lib/x86_64-linux-gnu/libcanberra.so.0.2.5
7fc41ca15000-7fc41ca19000 r-xp 00000000 08:05 4849794                    /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0.1.9
7fc41ca19000-7fc41cc18000 ---p 00004000 08:05 4849794                    /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0.1.9
7fc41cc18000-7fc41cc19000 r--p 00003000 08:05 4849794                    /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0.1.9
7fc41cc19000-7fc41cc1a000 rw-p 00004000 08:05 4849794                    /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0.1.9
7fc41cc1a000-7fc41cc1f000 r-xp 00000000 08:05 5114456                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
7fc41cc1f000-7fc41ce1e000 ---p 00005000 08:05 5114456                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
7fc41ce1e000-7fc41ce1f000 r--p 00004000 08:05 5114456                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
7fc41ce1f000-7fc41ce20000 rw-p 00005000 08:05 5114456                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libcanberra-gtk-module.so
7fc41ce20000-7fc41ce23000 r-xp 00000000 08:05 5112936                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libadwaita.so
7fc41ce23000-7fc41d022000 ---p 00003000 08:05 5112936                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libadwaita.so
7fc41d022000-7fc41d023000 r--p 00002000 08:05 5112936                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libadwaita.so
7fc41d023000-7fc41d024000 rw-p 00003000 08:05 5112936                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libadwaita.so
7fc41d024000-7fc41d02e000 r-xp 00000000 08:05 5111989                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7fc41d02e000-7fc41d22d000 ---p 0000a000 08:05 5111989                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7fc41d22d000-7fc41d22e000 r--p 00009000 08:05 5111989                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7fc41d22e000-7fc41d22f000 rw-p 0000a000 08:05 5111989                    /usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines/libpixmap.so
7fc41d22f000-7fc41d25b000 r-xp 00000000 08:05 4868289                    /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
7fc41d25b000-7fc41d45a000 ---p 0002c000 08:05 4868289                    /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
7fc41d45a000-7fc41d45d000 r--p 0002b000 08:05 4868289                    /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
7fc41d45d000-7fc41d45e000 rw-p 0002e000 08:05 4868289                    /usr/lib/x86_64-linux-gnu/libatspi.so.0.0.1
7fc41d45e000-7fc41d48b000 r-xp 00000000 08:05 4868295                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
7fc41d48b000-7fc41d68a000 ---p 0002d000 08:05 4868295                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
7fc41d68a000-7fc41d68b000 r--p 0002c000 08:05 4868295                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
7fc41d68b000-7fc41d68d000 rw-p 0002d000 08:05 4868295                    /usr/lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0.0.0
7fc41d68d000-7fc41d68e000 r-xp 00000000 08:05 5111846                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7fc41d68e000-7fc41d88d000 ---p 00001000 08:05 5111846                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7fc41d88d000-7fc41d88e000 r--p 00000000 08:05 5111846                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7fc41d88e000-7fc41d88f000 rw-p 00001000 08:05 5111846                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libatk-bridge.so
7fc41d88f000-7fc41d896000 r-xp 00000000 08:05 4854918                    /usr/lib/x86_64-linux-gnu/libgailutil.so.18.0.1
7fc41d896000-7fc41da95000 ---p 00007000 08:05 4854918                    /usr/lib/x86_64-linux-gnu/libgailutil.so.18.0.1
7fc41da95000-7fc41da96000 r--p 00006000 08:05 4854918                    /usr/lib/x86_64-linux-gnu/libgailutil.so.18.0.1
7fc41da96000-7fc41da97000 rw-p 00007000 08:05 4854918                    /usr/lib/x86_64-linux-gnu/libgailutil.so.18.0.1
7fc41da97000-7fc41dae5000 r-xp 00000000 08:05 5111990                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so
7fc41dae5000-7fc41dce4000 ---p 0004e000 08:05 5111990                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so
7fc41dce4000-7fc41dce5000 r--p 0004d000 08:05 5111990                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so
7fc41dce5000-7fc41dce7000 rw-p 0004e000 08:05 5111990                    /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so
7fc41dce7000-7fc41dcf9000 r-xp 00000000 08:05 2359706                    /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fc41dcf9000-7fc41def9000 ---p 00012000 08:05 2359706                    /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fc41def9000-7fc41defa000 r--p 00012000 08:05 2359706                    /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fc41defa000-7fc41defb000 rw-p 00013000 08:05 2359706                    /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fc41defb000-7fc41df11000 r-xp 00000000 08:05 2359462                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7fc41df11000-7fc41e110000 ---p 00016000 08:05 2359462                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7fc41e110000-7fc41e111000 r--p 00015000 08:05 2359462                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7fc41e111000-7fc41e112000 rw-p 00016000 08:05 2359462                    /lib/x86_64-linux-gnu/libnsl-2.23.so
7fc41e112000-7fc41e114000 rw-p 00000000 00:00 0 
7fc41e114000-7fc41e1ec000 r-xp 00000000 08:05 2359708                    /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7fc41e1ec000-7fc41e3eb000 ---p 000d8000 08:05 2359708                    /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7fc41e3eb000-7fc41e3ec000 r--p 000d7000 08:05 2359708                    /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7fc41e3ec000-7fc41e3f4000 rw-p 000d8000 08:05 2359708                    /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7fc41e3f4000-7fc41e3f5000 rw-p 00000000 00:00 0 
7fc41e3f5000-7fc41e3fa000 r-xp 00000000 08:05 4858809                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7fc41e3fa000-7fc41e5f9000 ---p 00005000 08:05 4858809                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7fc41e5f9000-7fc41e5fa000 r--p 00004000 08:05 4858809                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7fc41e5fa000-7fc41e5fb000 rw-p 00005000 08:05 4858809                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7fc41e5fb000-7fc41e603000 r-xp 00000000 08:05 2363769                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7fc41e603000-7fc41e802000 ---p 00008000 08:05 2363769                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7fc41e802000-7fc41e803000 r--p 00007000 08:05 2363769                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7fc41e803000-7fc41e804000 rw-p 00008000 08:05 2363769                    /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7fc41e804000-7fc41e805000 rw-p 00000000 00:00 0 
7fc41e805000-7fc41e80f000 r-xp 00000000 08:05 2363646                    /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7fc41e80f000-7fc41ea0e000 ---p 0000a000 08:05 2363646                    /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7fc41ea0e000-7fc41ea0f000 r--p 00009000 08:05 2363646                    /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7fc41ea0f000-7fc41ea10000 rw-p 0000a000 08:05 2363646                    /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7fc41ea10000-7fc41ea35000 r-xp 00000000 08:05 2359311                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fc41ea35000-7fc41ec34000 ---p 00025000 08:05 2359311                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fc41ec34000-7fc41ec38000 r--p 00024000 08:05 2359311                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fc41ec38000-7fc41ec39000 rw-p 00028000 08:05 2359311                    /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fc41ec39000-7fc41ecb2000 r-xp 00000000 08:05 5114328                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7fc41ecb2000-7fc41eeb1000 ---p 00079000 08:05 5114328                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7fc41eeb1000-7fc41eeb2000 r--p 00078000 08:05 5114328                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7fc41eeb2000-7fc41eeb3000 rw-p 00079000 08:05 5114328                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7fc41eeb3000-7fc41ef01000 r-xp 00000000 08:05 4868462                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7fc41ef01000-7fc41f100000 ---p 0004e000 08:05 4868462                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7fc41f100000-7fc41f101000 r--p 0004d000 08:05 4868462                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7fc41f101000-7fc41f102000 rw-p 0004e000 08:05 4868462                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7fc41f102000-7fc41f13f000 r-xp 00000000 08:05 2359693                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7fc41f13f000-7fc41f33f000 ---p 0003d000 08:05 2359693                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7fc41f33f000-7fc41f341000 r--p 0003d000 08:05 2359693                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7fc41f341000-7fc41f347000 rw-p 0003f000 08:05 2359693                    /lib/x86_64-linux-gnu/libreadline.so.6.3
7fc41f347000-7fc41f348000 rw-p 00000000 00:00 0 
7fc41f348000-7fc41f392000 r-xp 00000000 08:05 2359354                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7fc41f392000-7fc41f592000 ---p 0004a000 08:05 2359354                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7fc41f592000-7fc41f593000 r--p 0004a000 08:05 2359354                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7fc41f593000-7fc41f594000 rw-p 0004b000 08:05 2359354                    /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7fc41f594000-7fc41f597000 r-xp 00000000 08:05 4850579                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7fc41f597000-7fc41f797000 ---p 00003000 08:05 4850579                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7fc41f797000-7fc41f798000 r--p 00003000 08:05 4850579                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7fc41f798000-7fc41f799000 rw-p 00004000 08:05 4850579                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7fc41f799000-7fc41f892000 r-xp 00000000 08:05 4851713                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fc41f892000-7fc41fa91000 ---p 000f9000 08:05 4851713                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fc41fa91000-7fc41fa98000 r--p 000f8000 08:05 4851713                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fc41fa98000-7fc41fa99000 rw-p 000ff000 08:05 4851713                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7fc41fa99000-7fc41fadf000 r-xp 00000000 08:05 4858857                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7fc41fadf000-7fc41fcdf000 ---p 00046000 08:05 4858857                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7fc41fcdf000-7fc41fce1000 r--p 00046000 08:05 4858857                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7fc41fce1000-7fc41fce2000 rw-p 00048000 08:05 4858857                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7fc41fce2000-7fc41fd37000 r-xp 00000000 08:05 4852513                    /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1.5.2
7fc41fd37000-7fc41ff37000 ---p 00055000 08:05 4852513                    /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1.5.2
7fc41ff37000-7fc41ff38000 r--p 00055000 08:05 4852513                    /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1.5.2
7fc41ff38000-7fc41ff3a000 rw-p 00056000 08:05 4852513                    /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1.5.2
7fc41ff3a000-7fc41ffa8000 rw-p 00000000 00:00 0 
7fc41ffa8000-7fc41fff2000 r-xp 00000000 08:05 4859666                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7fc41fff2000-7fc4201f2000 ---p 0004a000 08:05 4859666                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7fc4201f2000-7fc4201f3000 r--p 0004a000 08:05 4859666                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7fc4201f3000-7fc4201f4000 rw-p 0004b000 08:05 4859666                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7fc4201f4000-7fc420333000 rw-p 00000000 00:00 0 
7fc420333000-7fc420365000 r-xp 00000000 08:05 4875399                    /usr/lib/x86_64-linux-gnu/libdumb.so.1.0.0
7fc420365000-7fc420564000 ---p 00032000 08:05 4875399                    /usr/lib/x86_64-linux-gnu/libdumb.so.1.0.0
7fc420564000-7fc420565000 r--p 00031000 08:05 4875399                    /usr/lib/x86_64-linux-gnu/libdumb.so.1.0.0
7fc420565000-7fc420566000 rw-p 00032000 08:05 4875399                    /usr/lib/x86_64-linux-gnu/libdumb.so.1.0.0
7fc420566000-7fc420567000 rw-p 00000000 00:00 0 
7fc420567000-7fc4205b2000 r-xp 00000000 08:05 4854832                    /usr/lib/x86_64-linux-gnu/libmpg123.so.0.41.2
7fc4205b2000-7fc4207b2000 ---p 0004b000 08:05 4854832                    /usr/lib/x86_64-linux-gnu/libmpg123.so.0.41.2
7fc4207b2000-7fc4207b3000 r--p 0004b000 08:05 4854832                    /usr/lib/x86_64-linux-gnu/libmpg123.so.0.41.2
7fc4207b3000-7fc4207b4000 rw-p 0004c000 08:05 4854832                    /usr/lib/x86_64-linux-gnu/libmpg123.so.0.41.2
7fc4207b4000-7fc4207c4000 rw-p 00000000 00:00 0 
7fc4207c4000-7fc4207cb000 r-xp 00000000 08:05 4859568                    /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.7
7fc4207cb000-7fc4209cb000 ---p 00007000 08:05 4859568                    /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.7
7fc4209cb000-7fc4209cc000 r--p 00007000 08:05 4859568                    /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.7
7fc4209cc000-7fc4209cd000 rw-p 00008000 08:05 4859568                    /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3.3.7
7fc4209cd000-7fc4209f7000 r-xp 00000000 08:05 4859738                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fc4209f7000-7fc420bf7000 ---p 0002a000 08:05 4859738                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fc420bf7000-7fc420bf8000 r--p 0002a000 08:05 4859738                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fc420bf8000-7fc420bf9000 rw-p 0002b000 08:05 4859738                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7fc420bf9000-7fc420c00000 r-xp 00000000 08:05 4859462                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fc420c00000-7fc420e00000 ---p 00007000 08:05 4859462                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fc420e00000-7fc420e01000 r--p 00007000 08:05 4859462                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fc420e01000-7fc420e02000 rw-p 00008000 08:05 4859462                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fc420e02000-7fc420e8f000 r-xp 00000000 08:05 4859517                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fc420e8f000-7fc42108e000 ---p 0008d000 08:05 4859517                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fc42108e000-7fc4210aa000 r--p 0008c000 08:05 4859517                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7fc4210aa000-7fc4210ab000 rw-p 000a8000 08:05 4859517                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11Abgebrochen (Speicherabzug geschrieben)

**Comment by abma** [comment] 2016-04-24 15:59
try to uninstall system installed spring, i.e. apt-get remove spring

very likely a duplicate of https://github.com/springlobby/springlobby/issues/707

**Comment by weingaunity** [comment] 2016-04-24 17:46
Due to some other issue i had to install my linux new.
I installed Springlobby 0.237 from ubuntu 16.04 repositories.

Started, all OK.

Then i copied the .spring .springlobby directories from my old account to the new one, System crashes.

So, there is some issue with the content of these directories. If i delete it and springlobby creates new one, all is OK.

I do not investigated this issue in more detail until now. Maybe i will continue with testing, but currently i do not have time.

**Comment by abma** [comment] 2016-04-24 17:50
did you uninstall spring? when installing springlobby it automaticly installs spring, too which causes this crash.

**Comment by abma** [comment] 2016-05-02 20:29
no feedback -> duplicate of #707

**Closed by abma** 2016-05-02 20:29 UTC
Labels: bug, feedback
