### ISSUE TITLE
Springlobby segmentation fault crash

### ISSUE THREAD

**Issue by gajop** [springlobby/springlobby#727] opened 2016-07-08 02:31 UTC
Not really sure what caused it. I think I just started it again, but maybe 102 was downloaded by some other lobby? It could be a duplicate. The version is 0.247

The below is the crash stacktrace, seems like it fails when it tries to find the engine:
```
   from /home/gajop/.spring/engine/100.0/libunitsync.so
(gdb) bt
#0  0x00007fffd350322c in boost::object_cache<boost::re_detail::cpp_regex_traits_base<char>, boost::re_detail::cpp_regex_traits_implementation<char> >::do_get(boost::re_detail::cpp_regex_traits_base<char> const&, unsigned long) ()
   from /home/gajop/.spring/engine/100.0/libunitsync.so
#1  0x00007fffd3503941 in boost::shared_ptr<boost::re_detail::cpp_regex_traits_implementation<char> const> boost::re_detail::create_cpp_regex_traits<char>(std::locale const&) () from /home/gajop/.spring/engine/100.0/libunitsync.so
#2  0x00007fffd3503a22 in boost::re_detail::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::regex_data() () from /home/gajop/.spring/engine/100.0/libunitsync.so
#3  0x00007fffd3503f50 in boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int) () from /home/gajop/.spring/engine/100.0/libunitsync.so
#4  0x00007fffd33be083 in ?? () from /home/gajop/.spring/engine/100.0/libunitsync.so
#5  0x00007fffd33be60b in ?? () from /home/gajop/.spring/engine/100.0/libunitsync.so
#6  0x00007fffd33ab8b8 in ?? () from /home/gajop/.spring/engine/100.0/libunitsync.so
#7  0x00007fffd33ac49c in ?? () from /home/gajop/.spring/engine/100.0/libunitsync.so
#8  0x00007fffd339969d in ?? () from /home/gajop/.spring/engine/100.0/libunitsync.so
#9  0x00007ffff7de84aa in call_init.part () from /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff7de85bb in _dl_init () from /lib64/ld-linux-x86-64.so.2
#11 0x00007ffff7decae8 in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7de8354 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff7dec289 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#14 0x00007ffff59b7f09 in ?? () from /usr/lib/libdl.so.2
#15 0x00007ffff7de8354 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#16 0x00007ffff59b8541 in ?? () from /usr/lib/libdl.so.2
#17 0x00007ffff59b7fa2 in dlopen () from /usr/lib/libdl.so.2
#18 0x0000000000889256 in LSL::_LoadLibrary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#19 0x000000000084df68 in LSL::SpringBundle::GetBundleVersion() ()
#20 0x000000000084e8c0 in LSL::SpringBundle::AutoComplete(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#21 0x000000000085191c in LSL::SpringBundle::GetSpringVersionList(std::__cxx11::list<LSL::SpringBundle, std::allocator<LSL::Sp---Type <return> to continue, or q <return> to quit---
ringBundle> > const&) ()
#22 0x00000000007d99ca in SlPaths::RefreshSpringVersionList(bool, LSL::SpringBundle const*) ()
#23 0x00000000005abbb7 in SpringLobbyApp::OnInit() ()
#24 0x00007ffff6232202 in wxEntry(int&, wchar_t**) () from /usr/lib/libwx_baseu-3.0.so.0
#25 0x00000000004d32f8 in main ()
```

**Comment by abma** [comment] 2016-07-08 07:13
crash in unitsync / boost-regex -> duplicate of #707

**Comment by gajop** [comment] 2016-07-08 07:13
Sorry ;)

**Closed by abma** 2016-07-08 07:13 UTC
