### ISSUE TITLE
crash when trying to enter chicken defence v3.15 battleroom

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#436] opened 2015-05-15 09:36 UTC
I have a crash if I dont run using gdb. And I got a freeze when I run it with gdb:
http://pastebin.com/uBzCtMzT
(lobby was compilled from sources yesterday 0.219+)

**Comment by jamerlan** [comment] 2015-05-15 09:37
steps to reproduce:
just try to join battleroom with chicken defence v3.15

**Comment by abma** [comment] 2015-05-20 01:02
oh, duplicate of #444

http://paste.springfiles.com/view/raw/bee06e7f

**Closed by abma** 2015-05-20 01:02 UTC
Labels: bad bug
