### ISSUE TITLE
Notify user with tooltip when someone promotes battle?

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#401] opened 2015-04-09 18:52 UTC
Maybe this is a good idea? There are so many spectators ( > 20 ones) waiting for DSD at the full server. They don't even know that there are other battles, because they never look in chat when someone promotes new battle. With this notification (optional?) they could know that there is more than one place to play.

**Comment by abma** [comment] 2015-04-19 19:23
imo you are requesting here matchmaking:
https://springrts.com/phpbb/viewtopic.php?f=71&t=33072

duplicate of #144

**Closed by abma** 2015-04-19 19:23 UTC
