### ISSUE TITLE
allow to download by config value(s)

### ISSUE THREAD

**Issue by PicassoCT** [springlobby/springlobby#945] opened 2020-01-11 16:48 UTC
Is it possible to re-package the springlobby with a script, so that it autodownloads a map/game via rapid after installation?

**Comment by abma** [comment] 2020-01-12 22:49
currently no.

i guess best could be to ship it with a config file which contains some rapid tags / maps which are autodownloaded at start and when the files exists nothing is downloaded.

**Comment by abma** [comment] 2020-01-13 00:06
duplicate of #818

**Closed by abma** 2020-01-13 00:06 UTC
Labels: enhancement
