### ISSUE TITLE
SL freezes after every game ends

### ISSUE THREAD

**Issue by PtaQQ** [springlobby/springlobby#776] opened 2017-07-18 22:20 UTC
Probably a known bug, but to be sure: 
After game ends SL hangs for 10-20 sec, it is connected with reloading replays afaik, as clearing \demos folder fixes the issue.

**Comment by specing** [comment] 2017-07-19 21:50
I am experiencing the same, performance degrading with the increase in the number of replays. The same happens when sorting them in the replays tab, leading me to believe it is a performance issue with either sorting or WXWidgets or both.

**Comment by abma** [comment] 2017-07-20 11:38
@PtaQQ @specing 

are you using windows or linux?

**Comment by specing** [comment] 2017-07-20 12:12
GNU/Linux

**Comment by specing** [comment] 2017-09-21 22:40
Probably a duplicate of #717

**Comment by abma** [comment] 2018-02-20 18:40
yeah, duplicate

**Closed by abma** 2018-02-20 18:40 UTC
Labels: bug
