### ISSUE TITLE
Invisible player rows on player list

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#501] opened 2015-06-28 15:01 UTC
Sometimes when I join games the players on the player list don't show up, but they are there.

They are only "revealed" when I click on the list.

**Comment by springraaar** [comment] 2015-06-28 15:02
screenshot here : http://snag.gy/5BHGm.jpg

**Comment by abma** [comment] 2015-06-28 15:14
springlobby version? should be already fixed by most recent commits...

**Comment by abma** [comment] 2015-06-28 15:14
also very likely a duplicate of #418

**Comment by springraaar** [comment] 2015-06-28 15:17
version is 0.225

And you're right, it's probably a duplicate of 418.

**Comment by Usaga** [comment] 2015-06-28 16:45
This is <s>replaced by another bugs</s> fixed in development version

**Closed** 2015-06-29 00:57 UTC
Labels: feedback
