### ISSUE TITLE
Crash on start of 0.218 in ubuntu 15.04

### ISSUE THREAD

**Issue by ashdnazg** [springlobby/springlobby#426] opened 2015-05-08 20:28 UTC
I'm posting it for dust (whoever that is) so I'm unable to answer questions.

http://paste.springfiles.com/view/bc35da82

SL crashes consistently on startup.

```
SpringLobby version 0.218
Built from wxWidgets 3.0.2 on Linux

Call stack:
0x7f20e5f0811c 
0x7f20e786dd10 
0x56a93c IBattle::OnUserAdded(User&)
0x53827d Battle::OnUserAdded(User&)
0x58dd51 ServerEvents::OnUserJoinedBattle(int, std::string const&, std::string const&)
0x5d5ccb TASServer::ExecuteCommand(std::string const&, std::string const&, int)
0x5de3d1 TASServer::ExecuteCommand(std::string const&)
0x5dec35 TASServer::OnDataReceived()
0x597e88 Socket::OnSocketEvent(wxSocketEvent&)
0x7f20e5d9571e wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const
0x7f20e5f30f08 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
0x7f20e5f3100b wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
0x7f20e5f313b8 wxEvtHandler::TryHereOnly(wxEvent&)
0x7f20e5f31443 wxEvtHandler::ProcessEventLocally(wxEvent&)
0x7f20e5f314a5 wxEvtHandler::ProcessEvent(wxEvent&)
0x7f20e5f32638 wxEvtHandler::ProcessPendingEvents()
0x7f20e5d99697 wxAppConsoleBase::ProcessPendingEvents()
0x7f20e6444e02 wxApp::DoIdle()
0x7f20e6444f43 
0x7f20e38c6b4d g_main_context_dispatch
0x7f20e38c6f20 
0x7f20e38c7242 g_main_loop_run
0x7f20e1cfe857 gtk_main
0x7f20e6466745 wxGUIEventLoop::DoRun()
0x7f20e5ddb750 wxEventLoopBase::Run()
0x7f20e5d97a46 wxAppConsoleBase::MainLoop()
0x7f20e5e32660 wxEntry(int&, wchar_t**)
0x4d4f98 main
0x7f20e414ea40 __libc_start_main
0x5253e9 _start

sound=1
```

**Comment by abma** [comment] 2015-05-08 21:47
duplicate of #425

(as MajBoredom can give feedback i close this one)

**Comment by do2005** [comment] 2015-05-08 21:47
I have the same at Win7 x86. I'ts began today.

**Closed** 2015-05-08 21:47 UTC
