### ISSUE TITLE
Broken with latest uber-server

### ISSUE THREAD

**Issue by joeyhub** [springlobby/springlobby#850] opened 2018-04-05 18:23 UTC
When I connect to the latest uberserver springlobby disconnects instantly while asking me to accept the fingerprint. None of the buttons do anything.

Sometimes it goes mental, flickers and crashes.

Currently LAN play is impossible with springlobby.

**Comment by joeyhub** [comment] 2018-04-05 18:28
The only workaround is to downgrade to 260.

**Comment by joeyhub** [comment] 2018-04-05 20:25
OS: Windows

**Comment by abma** [comment] 2018-04-05 22:30
duplicate of #828

**Closed by abma** 2018-04-05 22:30 UTC
