### ISSUE TITLE
User has to scroll list of battles to click "Join" button.

### ISSUE THREAD

**Issue by jet-bird** [springlobby/springlobby#395] opened 2015-04-07 12:09 UTC
![join button aligned right](https://cloud.githubusercontent.com/assets/9379087/7022696/108afcea-dd37-11e4-818f-b0dc97ca928f.jpg)

**Comment by jet-bird** [comment] 2015-04-07 12:11
Screen resolution is 1366х768.

**Comment by jet-bird** [comment] 2015-04-07 13:52
Sorry, I misunderstood the bug report. And the image is wrong ) But you can see the problem with "Watch" , "Delete" and "Reload" buttons on the "Replays" tab here. And the same situation with "Join" button on the "Battlelist" tab.

**Comment by abma** [comment] 2015-04-07 14:02
duplicate of  related to  #159 & #165

**Comment by do2005** [comment] 2015-04-07 14:29
It's related with resize of Lobby, but it's issue wasn't described. Issue occurs only at replays page only.

**Comment by Usaga** [comment] 2015-04-11 10:52
Remove springlobby.conf it may help.

**Comment by do2005** [comment] 2015-04-11 11:07
Deleted springlobby.conf, nothing changed.

**Closed** 2015-04-19 12:57 UTC
Labels: bug
