### ISSUE TITLE
springlobby crash in unitsync <= 101.0 when mixing system installed and official static builds (crashes in libstdc++ due abi change)

### ISSUE THREAD

**Issue by eshattow** [springlobby/springlobby#707] opened 2016-04-13 16:18 UTC
Steps to reproduce:
1. rm -fr $springdir/engine/*
2. start spring, login, join battle for new test engine "101.0.1-255-g4f9a6d2 develop", confirm to download.
3. Crash.  See gdb backtrace (attached).  Springlobby aborts any time that $springdir/engine/"101.0.1-255-g4f9a6d2 develop" engine data is present.
[springlobby0244gdb-backtrace.txt](https://github.com/springlobby/springlobby/files/217505/springlobby0244gdb-backtrace.txt)

**Comment by abma** [comment] 2016-04-15 00:01
can you confirm that it is a duplicate of #656?

which version of springlobby are you using?

**Comment by eshattow** [comment] 2016-04-15 01:36
Version 0.244 is the one that is crashing, kind of the opposite of what you're expecting, Version 0.243 and earlier are okay no crash there.

**Comment by abma** [comment] 2016-04-15 01:41
thats really weird. can you fetch the debug symbols from unitsync and debug with these?

http://springrts.com/dl/buildbot/default/develop/101.0.1-255-g4f9a6d2/linux64/%7bdevelop%7d101.0.1-255-g4f9a6d2_spring_dbg.7z

basicly its unitsync which causes the crash, so this should be fixed.

i thought the crash is fixed by https://github.com/spring/spring/commit/8e87cc16ebf2be1d6ae655b5db8ffbd31d8882ad but it seems, it is not.

see the spring engine report:
https://springrts.com/mantis/view.php?id=5050

**Comment by abma** [comment] 2016-04-15 02:02
also do you have a system installed spring which is detected by springlobby?

**Comment by eshattow** [comment] 2016-04-15 03:52
Yes. Now I've modified the package of springlobby 0.244 that I've built to not require spring, and removed the system installed spring, and springlobby does not crash.

**Comment by abma** [comment] 2016-04-15 16:42
which version was the system installed spring?

**Comment by eshattow** [comment] 2016-04-15 23:59
System installed spring was http://ftp.us.debian.org/debian/pool/main/s/spring/spring_101.0+dfsg-2_amd64.deb

**Comment by pAULSG1** [comment] 2016-04-16 15:25
+1 for this issue
Springlobby 0.244. I've tried different Spring versions: 98, 100 and 101 - same problem. There were no issues with 0.242.

**Comment by abma** [comment] 2016-04-16 16:10
this is an bug in unitsync, a stacktrace with debug symbols of unitsync is needed.

**Comment by abma** [comment] 2016-04-16 16:12
as workarround i can only remove autodetection of system installed spring/unitsync

**Comment by pAULSG1** [comment] 2016-04-16 16:36
Hmm, I'd suggest checkbox in SL preferences dialog so it doesn't autoconfigure systen installed Spring if checked (or unchecked). This would be way safer than removing support for system installed Spring - just in case it's fixed one day or another or for people it actually works :)

For the moment being I gave up on using system installed Spring... unless you want my stacktrace I'll keep it this way.

**Comment by abma** [comment] 2016-04-16 16:36
> For the moment being I gave up on using system installed Spring... unless you want my stacktrace I'll keep it this way.

with debug symbols of unitsync, yes.

**Comment by pAULSG1** [comment] 2016-04-16 19:07
I hope this is what you asked for: [springlobby.trace.txt](https://github.com/springlobby/springlobby/files/222355/springlobby.trace.txt). If not please provide me some details on what to do - I rarely do any C/C++ debugging under Linux :P
I tested using SpringLobby 0.244, Spring 100 in system and Spring 101 in engines dir.

**Comment by abma** [comment] 2016-04-16 19:13
thanks!

oh, oops. this crash will be fixed with spring 102:

https://github.com/spring/spring/commit/8e87cc16ebf2be1d6ae655b5db8ffbd31d8882ad

**Comment by pAULSG1** [comment] 2016-04-16 19:15
Thanks for info! Luckily there's RC1 already out... too bad some mods lag behind releases :(

**Comment by abma** [comment] 2016-04-16 19:35
i'll leave this report open until spring 102.0 is released

**Comment by abma** [comment] 2016-07-07 10:14
"apt-get remove spring" ?!

**Comment by pcdummy** [comment] 2016-07-07 11:18
springlobby needs spring to run.

**Comment by pcdummy** [comment] 2016-07-07 11:20
Did another test with 0.247, crashes only when joining my TA host ([FAST]Autohost1)

**Comment by pcdummy** [comment] 2016-07-07 11:21
The old 0.237 which comes with Xenial works.

**Comment by abma** [comment] 2016-07-07 12:00
> springlobby needs spring to install.

thats an invalid dependency. you can remove "sudo rm /usr/lib/libunitsync.so" as workarround

**Comment by pcdummy** [comment] 2016-07-07 12:59
$ sudo rm -f /usr/lib/spring/libunitsync.so

worked for me, thanks @abma!

**Comment by pAULSG1** [comment] 2016-07-07 13:02
Hmm, problem occurs only if you use external repository, for example getdeb. There are several solutions:
1. Use system repository only :)
2. Wait for proper update in Ubuntu repositories by holding old springlobby package (apt-mark hold springlobby) - this way other packages are still updated.
3. Compile SL by yourself - no need for spring package.
4. Remove spring. You can do it by removing SL dependency on spring (remove:
_, spring (>= 0.81.2.1+dfsg1-5)_
from SL.package.deb/control.tar.gz/control .
5. Remove problematic library as **abma** suggested (sudo rm /usr/lib/libunitsync.so).
6. Replace spring binaries from package using 102 binaries.
7. Use other lobby.
8. Give up on spring and play other games.
1-3 are by the book solutions. 4-6... well, they are not as nice but still they work. 7-8 simply search for alternatives - because you report problem here I guess you don't consider them :)

Eh, I see I'm a bit too slow :P

**Comment by abma** [comment] 2016-07-07 13:03
idk who created the package for getdeb, so idk where to report he bug that springlobby depends on spring in this package which is the cause for this problem.

**Comment by pAULSG1** [comment] 2016-07-07 13:07
Hmm, good thinking: http://www.playdeb.net/contact/ . I think lobby dev opinion will be handled better/faster :)

**Comment by pcdummy** [comment] 2016-07-07 13:28
The package in the Ubuntu repo has the same dependency, i think getdeb clones that package and updates the sources.

**Comment by abma** [comment] 2016-07-07 14:04
@apoleon: am i right that you are the maintainer of the springlobby package for debian?

if so: does the current package of springlobby still depend on spring? if so: can you please remove this dependency or at least make the dependency optional as spring isn't required to run springlobby: chatting is possible without spring and springlobby can download an engine when needed.

FYI: this specific crash should be fixed with spring >=102.0.

**Comment by apoleon** [comment] 2016-07-07 14:22
On 07.07.2016 16:04, abma wrote:
> @apoleon <https://github.com/apoleon>: am i right that you are the
> maintainer of the springlobby package for debian?

Yes, I'm the maintainer of spring and springlobby for Debian.


> if so: does the current package of springlobby still depend on spring?

Yes.

> if so: can you please remove this dependency or at least make the
> dependency optional as spring isn't required to run springlobby:
> chatting is possible without spring and springlobby can download an
> engine when needed.
> 
> FYI: this specific crash should be fixed with spring >=102.0.

I'm not sure how this is related to Debian. It was always possible to
install multiple engines and to choose the one you want to play with. Of
course we highly recommend to use Debian's system spring engine because
it is built with system libraries and fully integrated into the system.
Debian is up-to-date, so is Ubuntu which simply pulls and recompiles the
packages from Debian.

Playdeb.net is not an official Debian service.

Is there a patch for this issue in spring/springlobby, so that we can
use it to address this issue?

I think we can relax the dependency on spring to Recommends but this
appears to be a workaround for something and not the solution.

**Comment by abma** [comment] 2016-07-07 14:56
> Is there a patch for this issue in spring/springlobby, so that we can use it to address this issue?

yes, https://github.com/spring/spring/commit/8e87cc16ebf2be1d6ae655b5db8ffbd31d8882ad

> I'm not sure how this is related to Debian. It was always possible to install multiple engines and to choose the one you want to play with. Of course we highly recommend to use Debian's system spring engine because it is built with system libraries and fully integrated into the system. Debian is up-to-date, so is Ubuntu which simply pulls and recompiles the packages from Debian.

does that mean debian "always" had the newest version of spring available?

> I think we can relax the dependency on spring to Recommends but this appears to be a workaround for something and not the solution.

hm, when debian has the latest version of spring available the problem seems ubuntu specific. :-|

**Comment by apoleon** [comment] 2016-07-07 15:20
On 07.07.2016 16:56, abma wrote:
>     Is there a patch for this issue in spring/springlobby, so that we
>     can use it to address this issue?
> 
> yes, spring/spring@8e87cc1
> <https://github.com/spring/spring/commit/8e87cc16ebf2be1d6ae655b5db8ffbd31d8882ad>

Ok, thanks. I think we can wait until spring 102 is released which
appears to happen this summer.


>     I'm not sure how this is related to Debian. It was always possible
>     to install multiple engines and to choose the one you want to play
>     with. Of course we highly recommend to use Debian's system spring
>     engine because it is built with system libraries and fully
>     integrated into the system. Debian is up-to-date, so is Ubuntu which
>     simply pulls and recompiles the packages from Debian.
> 
> does that mean debian "always" had the newest version of spring available?

In the last three years I have always packaged the latest release as
soon as it was available. If you follow Debian testing/unstable you will
always be up-to-date. Of course due to the nature of distributions older
versions of spring/springlobby exist because back then they were recent
and now the game has progressed. You can always recompile a newer
version and backport that to your system or just download a newer spring
engine with springlobby if you trust that program. ;)

Why has nobody suggested to modify the settings in springlobby and to
remove the system engine? (rm /usr/lib/spring/* is bad) Applying the
patch to the Ubuntu package would have been another alternative.

>     I think we can relax the dependency on spring to Recommends but this
>     appears to be a workaround for something and not the solution.
> 
> hm, when debian has the latest version of spring available the problem
> seems ubuntu specific. :-|

We are not tracking RC releases or even Git snapshots but as soon as new
versions got released we will package them and then they will
automatically migrate to Ubuntu.

Fastest way to get a Debian specific bug fixed is to report it.

https://www.debian.org/Bugs/Reporting

**Comment by abma** [comment] 2016-07-07 16:26
> Ok, thanks. I think we can wait until spring 102 is released which appears to happen this summer.

spring 102.0 was released today ;-)

> Why has nobody suggested to modify the settings in springlobby and to remove the system engine? (rm /usr/lib/spring/* is bad) Applying the patch to the Ubuntu package would have been another alternative.

its just a workarround... the cause is the broken unitsync.

**Comment by abma** [comment] 2018-02-20 18:36
nevery heard about such a crash for a very long time: i assume this as fixed.

**Closed by abma** 2018-02-20 18:36 UTC
Labels: bug
