### ISSUE TITLE
on windows 8.1 springlobby starts but inside frame is white

### ISSUE THREAD

**Issue by Lowdive** [springlobby/springlobby#447] opened 2015-05-18 19:22 UTC
all you can see is the options menu, graphically all the inside of the springlobby window is white, you can't select multiplayer, singleplayer, replays, chat, battleroom...
you can't see what's going on even though the program is running and the client is indeed connected to server.
all you get is the frame of the window and the window options menu: connect, options, help, etc.

**Comment by Lowdive** [comment] 2015-05-18 19:22
springlobby version 0.219

**Comment by abma** [comment] 2015-05-18 19:26
VERY likely a duplicate of #418

thanks for reporting!

**Comment by abma** [comment] 2015-05-28 00:42
can you make a screenshot please?

also, does it show something when you resize the window?

**Closed** 2015-06-04 19:27 UTC
Labels: bad bug
