### ISSUE TITLE
I have maps and games but lobby is still trying to download them

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#645] opened 2016-03-09 18:25 UTC
https://youtu.be/SrNERm1XmGA
0.243-188-g82e5043

these bugs I reported in https://github.com/springlobby/springlobby/issues/643
looks like they were not fixed

how to reproduce:
1) delete all engines
2) open lobby
3) try to join battle

BTW: why maps and games are not visible without engine? This is very strange.

**Comment by abma** [comment] 2016-03-10 00:09
springlobby requires an engine to find maps / games. without it can't find them.

idk how to cleanly solve this. usally you don't delete all engines.

**Comment by jamerlan** [comment] 2016-03-10 06:33
You can, for example: 
1) download engine 
2) apply engine (maps and games should be found after engine downloading, currently they are not)
3) download map and game only if they are missing

**Comment by Usaga** [comment] 2016-03-10 09:06
Strange. If lobby started without any engine it should ask for download one... So no need to download it only to check if map\game exists.

**Comment by jamerlan** [comment] 2016-03-10 19:22
yep. It is asking to download. I just started lobby, it downloaded engine. And then.. no maps or games detected. Only engine is marked as resolved. So please stop refusing to fix it :-D and be "owners" of this project. You guys is the only hope.

**Comment by abma** [comment] 2016-03-10 19:39
> You can, for example:
> 1) download engine
> 2) apply engine (maps and games should be found after engine downloading, currently they are not)
> 3) download map and game only if they are missing

thats how it currently works. a "normal user" doesn't delete all engines.

**Comment by jamerlan** [comment] 2016-03-10 20:27
"Normal user" can install/reinstall lobby without engines

**Comment by abma** [comment] 2016-03-10 21:20
sorry, can't reproduce this issue.

can you please retest with current version / provide the output of
springlobby -cl -l9

when it still fails for you?

**Comment by jamerlan** [comment] 2016-03-10 21:42
0.243-191-ge752d75
https://youtu.be/2peAdHVC_QA
http://pastebin.com/vDL5xVXE
this time even downloading progress bar is gone

**Comment by abma** [comment] 2016-04-03 13:51
should be fixed

**Closed by abma** 2016-04-03 13:51 UTC
Labels: feedback
