### ISSUE TITLE
yet another lobby crash

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#543] opened 2015-08-11 08:34 UTC
lobby was IDLE. I was not even in the battleroom. Lobby was just opened to receive messages during the night.
http://pastebin.com/qy8f9mjS

0.225-180-gbd656ae

**Comment by abma** [comment] 2015-08-11 09:00
duplicate of #533 

stacktrace is similar/the same:

TASServer::OnDisconnected()

**Closed by abma** 2015-08-11 09:00 UTC

**Comment by abma** [comment] 2015-08-11 09:02
still thanks for reporting, this should makes reproducing it easer

**Comment by jamerlan** [comment] 2015-08-11 13:00
Yep, disconnect crashed lobby :-)
