### ISSUE TITLE
crash linux

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#634] opened 2016-02-13 13:24 UTC
latest lobby crashing very often

http://pastebin.com/MkAxuxWu
------------------------------------------------------------
SpringLobby 0.243-126-gb067f56 (unix x64)
SpringLobby config file: /home/revenant/.springlobby/springlobby.conf ( writable)
LobbyWriteDir (/home/revenant/.springlobby/)
	WX: yes POSIX: yes TRY: yes
CachePath (/home/revenant/.springlobby/cache/)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (/home/revenant/springlobby/src/)
	WX: yes POSIX: yes TRY: yes
DownloadDir (/home/revenant/.spring/)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (/home/revenant/.config/spring/)
	WX: yes POSIX: yes TRY: yes
Current unitsync: /usr/lib64/libunitsync.so
Current spring executable: /usr/bin/spring
Current uikeys.txt: /home/revenant/.config/spring/uikeys.txt
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
/home/revenant/springlobby/src/springlobby

**Comment by jamerlan** [comment] 2016-02-14 12:57
Also I have this: 
![slbug](https://cloud.githubusercontent.com/assets/216801/13033758/acf4be84-d333-11e5-8767-9050182a8ce0.png)

**Comment by jamerlan** [comment] 2016-02-14 13:21
+ crash when downloading new BA version:
4380/4384 checkedenant/springlobby/src/downloader/lib/src/Downloader/Rapid/Sdp.cpp:101:download(): 
4384/4384 need to download 0 files/src/downloader/lib/src/Downloader/Rapid/Sdp.cpp:104:download(): 
[Debug] /home/revenant/springlobby/src/downloader/lib/src/Downloader/Rapid/Sdp.cpp:118:download(): Already downloaded: ba:stable
[Debug] /home/revenant/springlobby/src/downloader/lib/src/Downloader/Http/HttpDownloader.cpp:501:download(): Nothing to download!
[Debug] /home/revenant/springlobby/src/downloader/lib/src/Downloader/Http/HttpDownloader.cpp:501:download(): Nothing to download!
[1]    20856 abort (core dumped)  /home/revenant/springlobby/src/springlobby

**Comment by abma** [comment] 2016-02-14 14:15
crash after download is a duplicate of #633 

i never saws the the "logic error message", is there a way to reproduce it or does it happen randomly?

**Comment by jamerlan** [comment] 2016-02-15 11:34
Often it crashes after battle end. You join battleroom, you play a game. Game ended -> crash

**Closed** 2016-02-15 22:01 UTC
Labels: bad bug, feedback
