### ISSUE TITLE
Springlobby crashes on startup

### ISSUE THREAD

**Issue by nnbosko** [springlobby/springlobby#566] opened 2015-09-27 03:55 UTC
Self descriptive. Here's the call stack.

```
Call stack:
0x7fdb12332340 
0x7fdb12067680 __longjmp_chk
0x7fdb145a22d0 wxPNGHandler::SaveFile(wxImage*, wxOutputStream&, bool)
0x7fdb0ec33216 png_error
0x7fdb0ec27cf8 png_create_read_struct_2
0x7fdb0ec27f17 png_create_read_struct
0x7fdb145a3c17 wxPNGHandler::LoadFile(wxImage*, wxInputStream&, bool, int)
0x7fdb14592668 wxImage::DoLoad(wxImageHandler&, wxInputStream&, int)
0x7fdb145928cf wxImage::LoadFile(wxInputStream&, wxBitmapType, int)
0x747c9d charArr2wxBitmap(unsigned char const*, int)
0x567e65 IconImageList::IconImageList()
0x56909a icons()
0x625176 MainWindow::MainWindow()
0x658937 Ui::Ui()
0x658bc5 ui()
0x66eb10 NotificationManager::NotificationManager()
0x66ee85 notificationManager()
0x59644d SpringLobbyApp::OnInit()
0x7fdb13e6363c wxEntry(int&, wchar_t**)
0x4d1da8 main
0x7fdb11f7dec5 __libc_start_main
0x51f765 _start
```

SystemInfos.txt:
SpringLobby version 0.226-51-gcec49ab
Built from wxWidgets 3.0.2 on Linux

**Comment by nnbosko** [comment] 2015-09-27 03:55
The OS is Linux Mint 17.

**Comment by abma** [comment] 2015-09-27 10:46
please update to the latest version (>=0.226-56-g88dbd14) as it possible already contains a fix.

**Comment by nnbosko** [comment] 2015-09-28 22:47
I downloaded the newest git version as per instructions (git clone --recursive), followed the building instructions and I am getting the same error.

Sysinfo: SpringLobby version 0.231-2-gfaa7322
Built from wxWidgets 3.0.2 on Linux

Stack trace:
Call stack:
0x7f6ab43ca340 
0x7f6ab40ff680 __longjmp_chk
0x7f6ab66b72d0 wxPNGHandler::SaveFile(wxImage*, wxOutputStream&, bool)
0x7f6ab0ccb216 png_error
0x7f6ab0cbfcf8 png_create_read_struct_2
0x7f6ab0cbff17 png_create_read_struct
0x7f6ab66b8c17 wxPNGHandler::LoadFile(wxImage*, wxInputStream&, bool, int)
0x7f6ab66a7668 wxImage::DoLoad(wxImageHandler&, wxInputStream&, int)
0x7f6ab66a78cf wxImage::LoadFile(wxInputStream&, wxBitmapType, int)
0x747ecd charArr2wxBitmap(unsigned char const*, int)
0x567fd5 IconImageList::IconImageList()
0x56920a icons()
0x625316 MainWindow::MainWindow()
0x658b57 Ui::Ui()
0x658de5 ui()
0x66ed40 NotificationManager::NotificationManager()
0x66f0b5 notificationManager()
0x5965ed SpringLobbyApp::OnInit()
0x7f6ab5f7863c wxEntry(int&, wchar_t**)
0x4d1f18 main
0x7f6ab4015ec5 __libc_start_main
0x51f8d5 _start

**Comment by abma** [comment] 2015-09-28 23:03
can you start it from console please with:

    springlobby -cl -l9

and paste the output to http://paste.springfiles.com please?

i'm on linux, too and don't get this crash, so i really need your help to fix this.

**Comment by nnbosko** [comment] 2015-09-28 23:04
Message  /home/bosko/Libraries/springlobby/src/springlobbyapp.cpp:119 SpringLobby 0.231-2-gfaa7322 started
Warning  /home/bosko/Libraries/springlobby/src/utils/slpaths.cpp:533 deleting /home/bosko/.springlobby/cache/
Warning  ./src/common/imagpng.cpp:167 Application was compiled with png.h from libpng-1.4.3
Warning  ./src/common/imagpng.cpp:167 Application  is  running with png.c from libpng-1.2.50
Warning  ./src/common/imagpng.cpp:167 Incompatible libpng version in application and library
Message  /home/bosko/Libraries/springlobby/src/crashreport.cpp:138 Report generated in 

I see the problem, that's strange. I think I'll remove --purge libpng, get the newest version and try again.

**Comment by nnbosko** [comment] 2015-09-28 23:05
http://paste.springfiles.com/view/1c3332e2 Sorry, didn't read that.

**Comment by abma** [comment] 2015-09-28 23:08
yeah, that should fix the bug. missmatch of header and library mostly causes crashes.

**Comment by abma** [comment] 2015-09-28 23:13
ldd springlobby

and 

   grep PNG_ CMakeCache.txt

should give hints about the used paths. i close this issue as imo its not a bug in springlobby. if you need further help, just respond here.

**Closed by abma** 2015-09-28 23:13 UTC
Labels: bad bug
