### ISSUE TITLE
LinuxMint 17.3 > With newest source, compilation makes SL not working

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#738] opened 2016-07-20 19:39 UTC
Today, I compiled SL.
I can't run it anymore.
In console, I got this many times :
~~~~
(springlobby:8815): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
Abandon
~~~~
(«Abandon» means = cancel)

or also :
~~~~
(springlobby:8819): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
*** Error in `./springlobby': malloc(): smallbin double linked list corrupted: 0x00000000031beba0 ***
Abandon
~~~~

AYMK, GTK issue always existed and I think this is not the problem.
I search and found this : http://stackoverflow.com/questions/19534051/glibc-detect-smallbin-linked-list-corrupted

Call me if you need some tests.

**Comment by abma** [comment] 2016-07-20 22:38
first you should try to do a clean compile, i.e.

    make clean && make

also possible a duplicate of #707.

**Comment by abma** [comment] 2016-07-28 14:03
no feedback -> closing

**Closed by abma** 2016-07-28 14:03 UTC
Labels: feedback

**Comment by FabriceFABS** [comment] 2016-07-28 20:23
Sorry I forgot it.

I didn't made `make clean && make`.
However, you surely changed something or... Because SL is working now after a successful compilation.
