### ISSUE TITLE
BattleList > Bots are not considered like players until you join a game

### ISSUE THREAD

**Issue by FabriceFABS** [springlobby/springlobby#712] opened 2016-04-22 18:53 UTC
1. I run SpringLobby, see the game highlighted, I know that there are 2 bots in it created from 3fm.
<img src="http://img11.hostingpics.net/pics/392168991.png">

2. I enter the game
<img src="http://img11.hostingpics.net/pics/311120342.png">

3. I check BattleList again, that now show all players in games (Humans & Robots)
<img src="http://img11.hostingpics.net/pics/480463563.png">

4. I leave the game, and the numbers of players are not correct again, like on Pic N°1.
<img src="http://img11.hostingpics.net/pics/125602204.png">

5. I ended my snapshots, entered again in [ACE]Pirateur game, and asked 3fm to remove his bots.

**Comment by silentwings** [comment] 2016-04-25 20:21
I have also noticed this and assumed it was intended behaviour.

**Comment by abma** [comment] 2016-04-26 09:31
maybe related to #714

**Comment by FabriceFABS** [comment] 2016-04-26 09:36
Do you think so ?
As you can see, bot got names, but maybe nothing regards to names and could be related to #714.

**Comment by abma** [comment] 2016-04-26 09:39
yes. as  the REMOVEBOT command fails, addbot is maybe invalid / incomplete, too.

http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#ADDBOT:client
http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#REMOVEBOT:client

could be a lobby server bug as well.

**Comment by abma** [comment] 2016-04-26 19:14
after some investigation:

thats wanted behaviour: basicly a bot isn't a player. also to fix this the lobby server needs to be changed. -> won't fix

**Closed by abma** 2016-04-26 19:14 UTC
