### ISSUE TITLE
 manually downloaded / extracted engine not detected correctly

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#644] opened 2016-03-08 13:52 UTC
https://youtu.be/vFg7u575MSk

0.243-180-g44f2fdf

**Comment by Usaga** [comment] 2016-03-08 13:59
This engine was downloaded by lobby or installed manualy?

**Comment by jamerlan** [comment] 2016-03-08 14:06
I tried both ways. Now I can't download 101 engine. When I select a battle with 101 engine and right click -> download spring... it downloads 101.bla-bla-bla (dev version).

**Comment by jamerlan** [comment] 2016-03-08 14:07
so currently 101 was installed manually. I tried to press "auto configure", "Apply" buttons - same result

**Comment by abma** [comment] 2016-03-08 14:40
whats the value in the fields "Location" of Spring executable and Unitsync library? its unreadable in the video.

do these files exist in the path? it looks like the file was manually extracted.

**Comment by jamerlan** [comment] 2016-03-08 16:54
current engine is: /home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static
paths in spring setting:
/home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/spring
/home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/libunitsync.so

both files exists:
➜  ~ ls -la /home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/spring
-rwxr-xr-x. 1 revenant revenant 16364984 Feb 29 00:07 /home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/spring
➜  ~ ls -la /home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/libunitsync.so
-rwxr-xr-x. 1 revenant revenant 2553032 Feb 29 00:07 /home/revenant/.spring/engine/spring_101.0_minimal-portable-linux64-static/libunitsync.so

problem is: lobby searching for another version of spring engine: 
![wrong_engine](https://cloud.githubusercontent.com/assets/216801/13608854/932deda4-e567-11e5-8612-5009a4fb39e8.png)

**Comment by abma** [comment] 2016-03-08 22:08
atm i see this as duplicate of #643

**Closed by abma** 2016-03-08 22:08 UTC
Labels: bug, feedback
