### ISSUE TITLE
springlobby network timeout after map download

### ISSUE THREAD

**Issue by supermuckl** [springlobby/springlobby#805] opened 2017-12-25 18:49 UTC
springlobby times out (network timeout), after a successful download of a missing map in battleroom after 90sec

official server tab output:

[19:46:50] ** Server ** Timeout assumed, disconnecting. Received no data from server for 90 seconds. Last ping send 20 seconds ago.
[19:46:50] ** Server ** Verbindung zum Server unterbrochen, Chat geschlossen.

battleroom output:

[19:46:50] ** Server ** Timeout assumed, disconnecting. Received no data from server for 90 seconds. Last ping send 20 seconds ago.
[19:46:50] ** Left Battle.

system: windows 10
springlobby ver: 0.260

SpringLobby 0.260 (win x32)
SpringLobby config file: C:\Users\super\AppData\Roaming\springlobby\springlobby.conf (writable)
LobbyWriteDir (C:\Users\super\AppData\Roaming\springlobby\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\super\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Program Files (x86)\SpringLobby\)
	WX: no POSIX: yes TRY: no
DownloadDir (C:\Users\super\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\super\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Users\super\Documents\My Games\Spring\engine\103.0\unitsync.dll
Current spring executable: C:\Users\super\Documents\My Games\Spring\engine\103.0\spring.exe
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Program Files (x86)\SpringLobby\springlobby.exe

**Comment by abma** [comment] 2017-12-27 14:24
can you add springlobby.log which contains this error?

**Comment by supermuckl** [comment] 2017-12-27 17:38
`Message  /data/private/buildbot/slaves/springlobby/release/build/src/springlobbyapp.cpp:124 SpringLobby 0.260 started
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/utils/wxTranslationHelper.cpp:26 Couldn't load locale 0, fallback to default
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) BATTLE
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\BATTLE.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/gui/playback/playbacktab.cpp:60 PlaybackTab::PlaybackTab()
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/springlobbyapp.cpp:182 SpringLobby 0.260 (win x32)
SpringLobby config file: C:\Users\super\AppData\Roaming\springlobby\springlobby.conf (writable)
LobbyWriteDir (C:\Users\super\AppData\Roaming\springlobby\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Users\super\AppData\Roaming\springlobby\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Program Files (x86)\SpringLobby\)
	WX: no POSIX: yes TRY: no
DownloadDir (C:\Users\super\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Users\super\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Users\super\Documents\My Games\Spring\engine\104.0.1-104-g2135e2e maintenance\unitsync.dll
Current spring executable: C:\Users\super\Documents\My Games\Spring\engine\104.0.1-104-g2135e2e maintenance\spring.exe
Portable mode: no
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Program Files (x86)\SpringLobby\springlobby.exe 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/utils/slconfig.cpp:84 config file saved: C:\Users\super\AppData\Roaming\springlobby\springlobby.conf
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) chatpanel-server
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\chatpanel-server.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) server
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\server.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #1 STLS
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:247 Starting TLS...
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:297 Certificate fingerprint: 0124dc0f4295b401a2d81ade3dc81b7a467eb9a70b0a4912b5e15fede735fe73
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:300 Using TLSv1.2
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:303 Using cipher ECDHE-RSA-AES256-GCM-SHA384
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1029 sent: LOGIN ... <password removed>
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) newbies
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\newbies.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) de
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\de.txt.
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #4 JOIN newbies 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #5 JOIN de 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #6 GETCHANNELMESSAGES newbies 339487
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #7 GETCHANNELMESSAGES de 337148
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514194610","msg":"Happy Xmas All","userName":"[FFA]VirtualP","chanName":"newbies","id":339501}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514208003","msg":"Merry Xmas to all","userName":"MasterHaidann","chanName":"newbies","id":339529}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514208947","msg":"Mery X-Men to you all!","userName":"[jw]Picasso","chanName":"newbies","id":339532}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514219732","msg":"I tried loading Gundam RTS/0.82.7 engine but it gave a modsum error. How do I fix the error? Or is that something the game developer needs to fix","userName":"Ulquiorra","chanName":"newbies","id":339581}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514219843","msg":"Ulquiorra dunno, but 0.82 is ancient","userName":"ThinkSome","chanName":"newbies","id":339582}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514220143","msg":"Ulquiorra could be that the game archive is broken?","userName":"ThinkSome","chanName":"newbies","id":339583}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:969 JSON {"SAID":{"time":"1514220521","msg":"gundam rts has been dead for many years","userName":"Code_Man","chanName":"newbies","id":339587}}
Message  /data/private/buildbot/slaves/springlobby/release/build/src/utils/slconfig.cpp:84 config file saved: C:\Users\super\AppData\Roaming\springlobby\springlobby.conf
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #73 JOINBATTLE 1933  08681e0c
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:195 Unitsync: Balanced Annihilation V9.46 OpenFileVFS: File 'sidepics/core.png' does not exist
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:195 Unitsync: Balanced Annihilation V9.46 ProcessUnits: luaParser.Execute() failed: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/featureDefs.lua, error = 2, gamedata/featuredefs_post.lua, [string "gamedata/featuredefs_post.lua"]:61: attempt to call field 'GetModOptions' (a nil value)


Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:110 OpenLogFile( ) _BATTLE_OverKillHost1
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:295 ChatLog::FillLastLineArray: Loaded 10 lines from C:\Users\super\AppData\Roaming\springlobby\chatlog\Official server\_BATTLE_OverKillHost1.txt.
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/gui/hosting/battleroomtab.cpp:459 Tag 3_mapname not found in options list
Message  /data/private/buildbot/slaves/springlobby/release/build/src/gui/customdialogs.cpp:83 The map neurope_a7 is required to play. Should it be downloaded?
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/log.cpp:195 received number 10000,000000 option limitscore exceeds boundaries 500,000000 5000,000000
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/serverevents.cpp:466 OnSetBattleInfo: Couldn't set game option limitscore
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/ibattle.cpp:795 Game doesn't exist
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/ibattle.cpp:70 Not synced: game name doesn't match host:'Balanced Annihilation V9.46' local:''
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #74 MYBATTLESTATUS 8390176 16229117
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/gui/ui.cpp:959 Required engine version doesn't match current selected version, switching to 103.0
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #75 MYBATTLESTATUS 4195872 16229117
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #76 MYBATTLESTATUS 4195872 16229117
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #81 EXIT Using http://springlobby.info/
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1046 sending: #1 LEAVEBATTLE failed
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #1 STLS
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:247 Starting TLS...
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:297 Certificate fingerprint: 0124dc0f4295b401a2d81ade3dc81b7a467eb9a70b0a4912b5e15fede735fe73
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:300 Using TLSv1.2
Message  /data/private/buildbot/slaves/springlobby/release/build/src/socket.cpp:303 Using cipher ECDHE-RSA-AES256-GCM-SHA384
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1029 sent: LOGIN ... <password removed>
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #4 JOIN newbies 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #5 JOIN de 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #6 JOIN de 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #7 JOIN newbies 
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #8 GETCHANNELMESSAGES newbies 339587
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #9 GETCHANNELMESSAGES de 337148
Warning  /data/private/buildbot/slaves/springlobby/release/build/src/gui/mainwindow.cpp:293 MainWindow::OnClose
Message  /data/private/buildbot/slaves/springlobby/release/build/src/tasserver.cpp:1044 sent: #969 EXIT Using http://springlobby.info/
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:64 newbies -- ChatLog::~ChatLog()
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:64 de -- ChatLog::~ChatLog()
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:64 server -- ChatLog::~ChatLog()
Message  /data/private/buildbot/slaves/springlobby/release/build/src/chatlog.cpp:64  -- ChatLog::~ChatLog()
Message  /data/private/buildbot/slaves/springlobby/release/build/src/utils/slconfig.cpp:84 config file saved: C:\Users\super\AppData\Roaming\springlobby\springlobby.conf
`

**Comment by abma** [comment] 2017-12-31 13:16
can you try again with springlobby 0.261 and post springlobby.log when it happened again please?

**Comment by supermuckl** [comment] 2018-01-05 22:25
running on 2.62 now - downloaded map - no problem
if i have it again, i will respond here

**Comment by abma** [comment] 2018-02-20 18:41
(VERY likely a duplicate of #717)

**Closed by abma** 2018-02-20 18:41 UTC
Labels: bug, feedback
