### ISSUE TITLE
(v0.210) adding new engine version/unitsync.dll takes very long (or hangs?)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#371] opened 2015-03-17 01:30 UTC
1) Preferences - add new engine version
2) select unitsync.dll
3) click ok
4) springlobby says: "SpringLobby is loading the 98.0.1-xxxxx engine unitsync library...."
5) Several minutes later: no progress and SL is still not presponding. 

![springlobby_adding_unitsync_takes_very_long_maybe_hangs](https://cloud.githubusercontent.com/assets/3044855/6679724/a261d61c-cc4c-11e4-9e34-42e607e34533.png)

**Comment by abma** [comment] 2015-03-17 01:43
duplicate of #48 

FYI: to speed up loading of unitsync reduce ammount of .sdd folders in the data dirs.

**Comment by knorker** [comment] 2015-03-17 01:43
it actually finished and worked.
took 15+ minutes though.
maybe just a case of "better GUI" or "faster unitsync" or something like that..

**Closed by abma** 2015-03-17 01:43 UTC
Labels: feature
