### ISSUE TITLE
Make SpringLobby to save files in it's own directory by default instead of

### ISSUE THREAD

**Issue by quantuumsnot** [springlobby/springlobby#868] opened 2018-05-24 17:23 UTC
... C:\Users\username\Documents\My Games\Spring

Because the directory grows too much on small SSDs

OS: Windows 7 x64

**Comment by specing** [comment] 2018-05-24 22:18
Which files? You can use symlinks to point subdirectories elsewhere.

**Comment by quantuumsnot** [comment] 2018-05-25 09:31
All downloaded files - maps, mods, engines

**Comment by abma** [comment] 2018-05-25 09:36
often springlobby is installed as admin and doesn't have write-access to the install dir.

you can configure the download dir in settings.

IMHO its ok as it is.

**Comment by quantuumsnot** [comment] 2018-05-25 09:38
So portable version is useless as variant? I always use it

imho hackish suggestions like symlinking directories breaks the user experience

**Comment by abma** [comment] 2018-05-25 09:47
duplicate of #584:

to avoid future misunderstanding i renamed portable to zip:
https://github.com/springlobby/springlobby-website/commit/6813d9f46f44bddfc899820e39c4ba00d09ca693


(will be applied to the webpage, soon)

**Closed by abma** 2018-05-25 09:47 UTC
Labels: feedback
