### ISSUE TITLE
Impossible to start "spring 104" game via singleplayer tab

### ISSUE THREAD

**Issue by jamerlan** [springlobby/springlobby#791] opened 2017-10-04 11:09 UTC
I have "spring 103" and "spring 104" - both downloaded by springlobby
When I go to "Singleplayer" and select 104 engine.. The game (BA) starts with 103 engine.
Lobby restart not helped. 
----------------------------
SpringLobby 0.258-1-g3e701d8 (unix x64)

**Comment by abma** [comment] 2017-10-04 12:27
do you have enough free disk space on the spring writeable dir? > 1GB is required.

atm there is no error message about this due to a bug in unitsync which is fixed in the development version of git (spring 104.0.1+): https://github.com/spring/spring/commit/e17ff8424bbaf15947f0bf042a276b43f0301a35

**Comment by jamerlan** [comment] 2017-10-04 14:07
Yep, I have 3 GB of free space

**Comment by jamerlan** [comment] 2017-10-04 14:10
I just reproduced again. Full log: 
https://pastebin.com/AvApjNfb

**Comment by jamerlan** [comment] 2017-10-04 14:11
If I join a battleroom with spring 104 - then spring 104 starts from battleroom.
I guess it is "singleplayer" related issue

**Comment by abma** [comment] 2017-10-04 16:11
does "double-select" the version work?

i.e. before clicking start, select some random version and then select 104.0 again and then click start?

**Comment by jamerlan** [comment] 2017-10-04 17:55
no, still starts spring 103

**Comment by abma** [comment] 2017-10-04 19:03
can you try again with the current springlobby version please and paste springlobby.log?

**Comment by jamerlan** [comment] 2017-10-04 19:40
Still not working. I tried both ways..
https://paste.fedoraproject.org/paste/ZW42mqQZxeEU5wqwoW~SQw

**Comment by jamerlan** [comment] 2017-10-04 19:55
Demo: https://youtu.be/LBiB1wZgOz4

**Comment by abma** [comment] 2017-10-05 01:32
"Going to start version 103"...

this makes me think 103.0 is selected :-| WEIRD!

**Comment by abma** [comment] 2017-10-05 01:39
when doing this: are you inside a battle?

**Comment by abma** [comment] 2017-10-05 02:04
please try again with b0530db5359d0b8afd4f1f2c87bf360fc62c3613. springlobby.log should lead to the cause of the problem.

**Comment by jamerlan** [comment] 2017-10-05 22:08
You fixed the issue! Thanks!
If you are still interested, here is the log: https://pastebin.com/JLW1ndib

**Comment by abma** [comment] 2017-10-05 23:22
in short: the code was WTF 😕

**Closed** 2017-10-05 23:21 UTC
Labels: feedback
