### ISSUE TITLE
error(s) when downloading engine

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#882] opened 2018-08-23 11:00 UTC
A lot of people have trouble getting a recent maintenance work. Also when i try to download a new engine myself it throws an error, but the download worked still (the error: "Failed to setup download 0/1")

Copy pasted the following said by Flaka:
i want to get a moment back from the discussion with rossco from last tuesday
https://cdn.discordapp.com/attachments/225695362004811776/481406036180467713/unknown.png

why do u think is the failure of the lobby?? i brought last week a new player into BA and unfortunately he had exaactly the same problems like rossco
he is able to install different spring versions but not the latest one which reminds me of my problem i had  until 2 months ago (just that i have found a workoaround -  which doesnt mean that the problem is resolved. its still there). anyway - if al spring versions till a certain date work and eveything after that date doesnt it the only logical reason where to look for the problem is spring and not anywhere else. . so devs should have a closer look to especially to the first version where the problem happens  or not? compare last working version with the version where the problem happens first time.

**Comment by Ruwetuin** [comment] 2018-08-23 11:19
additionally Flaka says that "...when all the older stuff till version 104.1.431 runs and everything after that version not.."

**Comment by silentwings** [comment] 2018-08-28 20:32
duplicate of https://github.com/springlobby/springlobby/issues/867

(Flakas issue was on mantis already iirc)

**Comment by fruehling76** [comment] 2018-08-31 06:31
yes it was on mantis and it was closed without resolving the Problem. i found a Workaround for me. but we are Talking of 2 different Problems 1. starting spring and running a game and 2. installing spring. 

those two Problems have one Thing in common: there is no Problem with the older Version - for case 1 it works unitl 431 if i remember correctly, for Problem 2 last working Version is 151 but we couldnt test 431 because it was not longer available. probably 431 is also working than the Situation is the same as for Problem 1. so i think there is Kind of bad Code somewhere in the spring enginges after Version 431 which causes al this difficulties and it has to be found because thats not a minor Thing - it happens to a lot of People.

**Comment by abma** [comment] 2018-09-01 19:28
no new version was fixed since it was fixed, sorry.

and yes, duplicate of #867

**Closed by abma** 2018-09-01 19:28 UTC
