### ISSUE TITLE
player wrongly shown as not synced on battle room, download file name issues

### ISSUE THREAD

**Issue by springraaar** [springlobby/springlobby#744] opened 2016-08-23 23:07 UTC
I was running a spads autohost, for metal factions v0.96   (http://springfiles.com/spring/games/metal-factions-12) with engine 100.0.

A player joined with springlobby 0.255 (same as mine), but he was unable to auto-download and would remain unsynced. The correct filename to download should be "metal_factions_v0.96.sdz", but maybe due to mirror issues and file name convention mixup it seems the lobby was trying to download "metal_factions-v0.96.sdz" instead.

After the player manually downloaded the game file and placed it in the games directory, he was still showing up as unsynced in the game room. Using the "reload maps/games" function in the lobby or restarting the lobby didn't fix the issue.

**Comment by springraaar** [comment] 2016-08-24 00:11
similar issue reported previously:

https://springrts.com/phpbb/viewtopic.php?t=34501

**Comment by abma** [comment] 2016-08-24 13:15
please provide the output of help->system info in springlobby from the player

**Comment by abma** [comment] 2016-08-24 17:28
> The correct filename to download should be "metal_factions_v0.96.sdz", but maybe due to mirror issues and file name convention mixup it seems the lobby was trying to download "metal_factions-v0.96.sdz" instead.

thats a wrong assumption. springfiles normalizes the filename -> use the normalized filenames!

for spring the filename doesn't matter it gets the checksum / archive by the contents not by the filename.

**Comment by springraaar** [comment] 2016-08-24 18:54
Springfiles only normalizes the filename sometimes. I don't care what it does internally, I shouldn't have to. If springfiles is going to change the filename for a downloaded file, it should either do it EVERY time or NEVER.

If what you wrote about the filename and the engine is true then, as the contents are the same, the player should show up as synced in the room and be able to play. He wasn't.

**Comment by springraaar** [comment] 2016-08-24 19:33
for example, go to springfiles, click on the 1v1 maps, "cattle and loveplay" map does have words and version separated with "-", but others like desolation, lunatic bowl and living lands use "_".

**Comment by abma** [comment] 2016-08-24 20:16
sorry, please stop guessing / assuming how stuff works.

i can only help you when you provide springlobby.log of the affected player.

i'm pretty sure the cause of the problem is not because of the filename.

**Comment by abma** [comment] 2016-08-24 21:16
maybe FYI: https://springrts.com/wiki/Springlobby.log

**Comment by springraaar** [comment] 2016-08-24 21:20
It's nluwdc_dust, did he send you the log?

He pasted on the chat this :
[21:56:25] <nluwdc_dust> Warning  /build/springlobby-nLdKuD/springlobby-0.255/src/log.cpp:169 Error: FIXME: Couldn't load the library /usr/lib/spring/libunitsync.so: /usr/lib/spring/libunitsync.so: cannot open shared object file: No such file or directory
[21:56:25] <nluwdc_dust> Warning  /build/springlobby-nLdKuD/springlobby-0.255/src/downloader/prdownloader.cpp:166 Couldn't reload unitsync!
[21:56:25] <nluwdc_dust> Warning  /build/springlobby-nLdKuD/springlobby-0.255/src/gui/iconscollection.cpp:235 SideIcon 0 for game Metal Factions v0.96 not found!

**Comment by springraaar** [comment] 2016-08-24 21:21
it wasn't like this before, but now it seems the log has private data, like chat logs and such, which can inhibit people from sharing it.

**Comment by abma** [comment] 2016-08-24 21:24
yeah, he should investigate why springlobby fails with this error:
"Couldn't load the library /usr/lib/spring/libunitsync.so: /usr/lib/spring/libunitsync.so: cannot open shared object file: No such file or directory"

**Comment by springraaar** [comment] 2016-08-27 04:40
I created a new version with the "-" as separator to avoid potential file naming issues. Today I restored the battle room and the player is still having the issue with the new version. This points to you being right about filename not being relevant.

**Comment by abma** [comment] 2016-09-07 23:19
no matter of what, this error needs to be fixed:

"[21:56:25] Warning /build/springlobby-nLdKuD/springlobby-0.255/src/log.cpp:169 Error: FIXME: Couldn't load the library /usr/lib/spring/libunitsync.so: /usr/lib/spring/libunitsync.so: cannot open shared object file: No such file or directory"

whats the output of "ldd /usr/lib/spring/libunitsync.so" ?

**Comment by abma** [comment] 2017-04-27 19:00
no feedback... closing

**Closed by abma** 2017-04-27 19:00 UTC
Labels: feedback
