### ISSUE TITLE
Wrong engine version detected

### ISSUE THREAD

**Issue by springjools** [springlobby/springlobby#370] opened 2015-03-16 15:23 UTC
![image](https://cloud.githubusercontent.com/assets/5911982/6669353/154e2a32-cc01-11e4-81ff-0a38d6f41448.png)

Sl detects engine 98.0 although host is running  98.0.1-390-g3615378

**Comment by abma** [comment] 2015-03-16 18:55
duplicate of \364

**Closed** 2015-03-16 18:56 UTC
