### ISSUE TITLE
Sometimes user list at battle room stops refresh

### ISSUE THREAD

**Issue by do2005** [springlobby/springlobby#418] opened 2015-05-02 21:13 UTC
It's old bug and it was fixed but at last version it's appears again.
![untitled-3](https://cloud.githubusercontent.com/assets/11837119/7442792/040d64b6-f129-11e4-8052-b4ceec326252.jpg)

Helps only "Reset layout" and restart lobby.

**Comment by richardba** [comment] 2015-05-02 22:09
I endorse

**Comment by abma** [comment] 2015-05-03 11:35
"sometimes" ... does it happen after map changes?

**Comment by do2005** [comment] 2015-05-03 18:16
At current moment i don't detected steps for reproducing of bug. But it's occurs often. Will try to detect.

**Comment by abma** [comment] 2015-05-05 22:24
maybe this?

https://support.microsoft.com/en-us/kb/3048761

(please install the update and test)

**Comment by do2005** [comment] 2015-05-05 23:18
OK, will be test

**Comment by do2005** [comment] 2015-05-09 00:08
Fix Installed. Issue is present.

**Comment by abma** [comment] 2015-05-20 01:55
can someone bisect this? i can't reproduce this bug on linux :-|

**Comment by Usaga** [comment] 2015-05-20 03:49
I will try. I see this bug sometimes.

**Comment by do2005** [comment] 2015-05-20 08:23
I have this issue very often, but i didn't found steps for reproduce

**Comment by knorker** [comment] 2015-05-27 15:55
This also happens on win vista and win 7.
I have seen it on v0.219 and on v0.222

It can be  "fixed" by clicking into the playerlist to highlight it
(like on https://cloud.githubusercontent.com/assets/11837119/7442792/040d64b6-f129-11e4-8052-b4ceec326252.jpg ) and then use up&arrow keys to "drive" up/down through it...that refreshes it and list becomes readable.
Bit quicker than restarting lobby all the time.

**Comment by abma** [comment] 2015-06-04 19:36
can you test if http://springlobby.info/temp/builds/abma/sl_master.zip fixed it for you please?

**Comment by abma** [comment] 2015-06-10 16:07
no feedback -> i assume it is fixed

**Comment by do2005** [comment] 2015-06-10 18:56
How it can be fixed if you didn't do new version? Still testing...

**Comment by abma** [comment] 2015-06-11 02:35
download the link i provided and test that version of springlobby...

**Comment by do2005** [comment] 2015-06-21 20:50
Last build - issue still present

**Comment by Usaga** [comment] 2015-06-22 10:57
We are working on it. List widgets are been reimplemented, it is need some time to finish. Please, wait.

**Comment by abma** [comment] 2015-07-20 09:12
should be fixed in development version

**Closed by abma** 2015-07-20 09:12 UTC
Labels: bad bug

**Comment by do2005** [comment] 2015-07-20 09:15
Issue still present!!! When it will be fixed at last?

**Comment by abma** [comment] 2015-07-20 09:19
which version are you using?

**Comment by do2005** [comment] 2015-07-20 09:26
0.225
