### ISSUE TITLE
Crash when trying to join a host. 

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#419] opened 2015-05-03 20:18 UTC
Happens nearly always after you have returned from an idle period.

**Comment by abma** [comment] 2015-05-03 20:19
windows/linux? springlobby version?

**Comment by Ruwetuin** [comment] 2015-05-03 20:28
windows 8.1, 0.218

**Comment by abma** [comment] 2015-05-03 20:33
do you join by double-click or by select item + join?

**Comment by Ruwetuin** [comment] 2015-05-03 21:14
doubleclick

**Comment by abma** [comment] 2015-05-03 21:34
i can't reproduce this crash, this is why i've to ask:
do you join hosts which use different engine versions?

**Comment by Ruwetuin** [comment] 2015-05-03 22:52
blackholehost 1 or 2 usually

**Comment by Usaga** [comment] 2015-05-05 17:41
This crash is showing itself only on Windows...

**Comment by do2005** [comment] 2015-05-06 18:11
This bug maybe connects with sorting of battle list. It is necessary to sort out the battle and then wait for auto-update list. Very often after this at click at battle opens other battle than i clicked or i got the crash.

**Comment by MajBoredom** [comment] 2015-05-08 19:12
Try running in debug mode / inside gdb and see if you can get a stack trace.

**Comment by abma** [comment] 2015-05-13 21:50
imo fixed: join via double click / button seems to work reliable...

fix will be included 0.220, if it doesn't work there please reopen or create a new bug report :)

thanks!

**Closed by abma** 2015-05-13 21:50 UTC
Labels: bug
