### ISSUE TITLE
springlobby crashes on startup

### ISSUE THREAD

**Issue by Ruwetuin** [springlobby/springlobby#394] opened 2015-04-05 07:17 UTC
Springlobby crashes on startup

I figured it happened after a settings change, springlobby.conf is responsible for this.

Its something to do with notifications(bottom right) and having configured a friends list. (already had it configured, just changed checkboxes)

after setting "UseNotificationPopups=0" it worked again.

**Comment by abma** [comment] 2015-04-05 11:33
duplicate of https://github.com/springlobby/springlobby/issues/385

**Closed by abma** 2015-04-05 11:33 UTC
