### ISSUE TITLE
Springlobby crashes when loading spring engine version 91.0

### ISSUE THREAD

**Issue by nyanpasu** [springlobby/springlobby#726] opened 2016-07-04 16:03 UTC
Using version `0.247-6-g2c468bb` of springlobby, and the portable compiled version of spring from [here](https://springrts.com/dl/buildbot/default/master/91.0/linux64/spring_91.0_minimal-portable-linux64-static.7z).

I extracted that archive to `~/.spring/engine/91.0/`

Crashes after:
 - logging in
 - Edit > Preferences
 - Add 91.0 files extracted
 - Select 91.0 profile
 - Pressing Apply/Ok

[Stack trace](http://hastebin.com/raw/egunutaney) with debug symbols for springlobby, but not libunitsync, unfortunately.

**Comment by abma** [comment] 2016-07-04 16:28
very likely a duplicate of #707 
(the same applies to mixing static builds + self-compiled builds)

possible 91.0 isn't supported at all, afaik some old spring/unitsync version had some crashbug.

**Comment by nyanpasu** [comment] 2016-07-05 02:11
I see. I think it crashes in different places. I'll try to debug with symbols.

Shame, because I'll have to downgrade springlobby in order to watch old replays or play older mods.

It's really cumbersome to use spring on its own.

**Comment by abma** [comment] 2016-07-10 11:20
/root/code/...

you really should NOT run spring / springlobby as root.

**Comment by nyanpasu** [comment] 2016-07-10 21:25
:^)

**Comment by abma** [comment] 2016-08-03 18:07
there are to many other issues / more important problems than fixing support for with a very old spring version.

this very likely is fixed when #48 is implemented, but i don't see me or anyone directly fix support for spring 91.0, sorry (and the real cause atm is unknown / very likely due to broken unitsync)

**Closed by abma** 2016-08-03 18:07 UTC
Labels: feedback
