### ISSUE TITLE
incorrect reaction to * as spring version

### ISSUE THREAD

**Issue by silentwings** [springlobby/springlobby#883] opened 2018-09-04 14:16 UTC
From https://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#TASSERVER:server
> Note that if the value of this parameter is "*", the client should simply ignore it since this means that the server does not contain any updates nor does it require latest Spring version 

SL tries to dl an engine version. (But tested only with 0.260, since #828 still exists.)

**Comment by abma** [comment] 2018-09-09 15:15
duplicate of #781 

current version of SL doesn't download the default version.

**Closed by abma** 2018-09-09 15:15 UTC
