### ISSUE TITLE
(v0.236) "Missing archive" on start, but was shown as synced (maybe mutator map)

### ISSUE THREAD

**Issue by knorker** [springlobby/springlobby#572] opened 2015-10-06 23:45 UTC
original map http://springfiles.com/spring/spring-maps/bluebend-v01

map that depends on the above map:
http://springfiles.com/spring/spring-maps/ba-bluebend-challengemap

1) SL shows as synced, but then on !start gives error:

![bla](https://cloud.githubusercontent.com/assets/3044855/10325767/9d7961f4-6c94-11e5-9197-45123f14854e.png)

After this:
2) I changed to the original map, to make it download that.

3) This map was then shown as synced

4) Change to the mutator-map again

5) Now the mutator-map was shown as unsynced. (before dl it had been shown as sync!)

Both original & mutator map were playable in spring/springlobby in ~2013

**Comment by knorker** [comment] 2015-10-07 00:04
The download works (as in: The file appears on the hard disk) but then still no synced.
For another player it works with TASClient but not with SL.

**Comment by abma** [comment] 2015-10-07 17:16
whats the output of help->system info and please provide infolog.txt!

**Comment by knorker** [comment] 2015-10-08 17:05
infolog lost.
But I just watched this replay on same mod+map:
http://replays.springrts.com/replay/b3548c553dbd4390f2c07a86c9ac602d/ and it worked, so all the files are there.
Right afterwards I select the map on semprini autohost and springlobby shows me as unsynced.
infolog from watching replay:
http://pastebin.com/7DmCnhbB

also in that replay was a player who could not download map too (dont know which lobby)

[f=0100346] > <flussjonas> hab probleme mit der map
[f=0100804] > <flussjonas> hab doxta aber spring meint es fehlt
[f=0100889] Connection attempt from flussjonas
[f=0100889]  -> Version: 98.0
[f=0100889]  -> Connection established (given id 4)
[f=0101215] <Raumfuellung> start mal lobby neu vllt
[f=0101484] <Raumfuellung> und die icy run map brauchts
[f=0101606] > <flussjonas> wenn ich starte will er aber icyrunv2.sd7 laden
[f=0101797] <Raumfuellung> ja, ladt das auch
[f=0102960] > <flussjonas> nein geht nicht


---
SpringLobby 0.236 (win x32)
SpringLobby config file: C:\Spiele\spring-98.0\springlobby.conf ( writable)
LobbyWriteDir (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
CachePath (C:\Spiele\spring-98.0\cache\)
	WX: yes POSIX: yes TRY: yes
ExecutableFolder (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
DownloadDir (C:\Users\dell\Documents\My Games\Spring\)
	WX: yes POSIX: yes TRY: yes
Current SpringData: (C:\Spiele\spring-98.0\)
	WX: yes POSIX: yes TRY: yes
Current unitsync: C:\Spiele\spring-98.0\unitsync.dll
Current spring executable: C:\Spiele\spring-98.0\spring.exe
Current uikeys.txt: C:\Spiele\spring-98.0\uikeys.txt
Portable mode: yes
Compiled with wxWidgets 3.0.2.0
Started with: 
C:\Spiele\spring-98.0\springlobby.exe

**Comment by abma** [comment] 2015-10-11 12:31
in which springsettings.cfg is SpringData = C:\Spiele\springcontent\ defined?

imo delete "C:\Spiele\spring-98.0\springsettings.cfg" + "C:\Users\dell\AppData\Local\springsettings.cfg" and your problems should be gone...

**Comment by knorker** [comment] 2015-10-12 14:19
> in which springsettings.cfg is SpringData = C:\Spiele\springcontent\ defined?
I add it to every springsettings.cfg that I can find, because _that_ is where I want files to be.
Of the .cfg-files listed in infolog that entry it is currently in:
"C:\Spiele\spring-98.0\springsettings.cfg"
"C:\Users\dell\Documents\My Games\Spring\springsettings.cfg"

"C:\Users\dell\AppData\Local\springsettings.cfg" is an empty file.
No idea if zero-K-lobby or spring.exe, or springlobby keep (re)creating those files and folders all over computer.

Also now I noticed that download-dir of springlobby has once again reseted to "my games"
 DownloadDir (C:\Users\dell\Documents\My Games\Spring)
despite that I always set it to "C:\Spiele\springcontent\", too.
(maybe from lobby update)

**Comment by abma** [comment] 2015-10-12 17:01
> I add it to every springsettings.cfg that I can find, because that is where I want files to be.

very likely thats the cause of this bug / problem.

>  Also now I noticed that download-dir of springlobby has once again reseted to "my games"

afaik this setting never was reset. maybe some invalid dir was entered?

**Comment by knorker** [comment] 2015-10-28 16:31
SL v0.243 and differnt PC (with no previous spring stuff)

The DOXTA v3 map is in downloads tab shown as "100%" but its minimap is displayed as blue emptiness:

![bla](https://cloud.githubusercontent.com/assets/3044855/10795313/70e4aab6-7d99-11e5-8a4f-af36f1c07147.png)

The metalmap & heightmap views work. Not sure if related to download, mutatormap or just random graphics bug.

**Comment by knorker** [comment] 2015-10-28 18:24
Also the sync-status in battlelist and battleroom contradict each other:
![bla](https://cloud.githubusercontent.com/assets/3044855/10798632/ee71ee44-7da8-11e5-88fc-9b652da00a77.png)

In maps folder there was downloaded **doxta_v3.sdz**
But **icyrun2.sdz7** (which the map depends on) was appearently not downloaded.

When trying to start the map in springlobby SP spring.exe also gives the message about archive icyrun2.sdz7 not found.

**Comment by knorker** [comment] 2015-10-28 18:35
Same situation with Spring1944 mutator: The mutatormod is downloaded, the base-mod not?
And battlelist shows "synced" when it is actually not synced.

![bla](https://cloud.githubusercontent.com/assets/3044855/10799021/e5c6be44-7daa-11e5-872a-dd54eebea066.png)

**Comment by knorker** [comment] 2015-10-28 18:56
springlobby downloaded spring__1944_equilibrio-1.75.sdz into the games\ folder instead of into rapid-pool system.

I manually downloaded the missing files with browser now:
s44-v2.0.sdz
 icyrun2.sdz

Afterwards both situations (xta doxta, S1944 mutator) synced.
=> Imo the problem is that springlobby did not download the derpendency files.

**Comment by abma** [comment] 2016-04-03 13:53
should be fixed, engine wasn't switched which very likely was causing this bug

**Closed by abma** 2016-04-03 13:53 UTC
Labels: feedback
